# Changes here will be overwritten by Copier
_commit: v1.4.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: t.j.wilson@exeter.ac.uk
author_name: Tom J Wilson
create_example_module: true
custom_install: true
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: lsdb_macauff
preferred_linter: pylint
project_license: BSD
project_name: lsdb_macauff
project_organization: macauff
use_gitlfs: none
use_isort: true
